aliases:
  - "fyrechatgame"
  - "chatgame"
  - "cg"

rewards:
  - "give {player} diamond_block 3"
  - "give {player} diamond_sword 1"
  - "give {player} apple 5"

random-characters:
  time: 10
  length: 8

math:
  time: 10
  problems:
    - "5 x 5 = 25"
    - "7 + 3 = 10"
    - "8 - 4 = 4"
    - "6 x 3 = 18"
    - "12 ÷ 4 = 3"
    - "9 + 6 = 15"
    - "15 - 7 = 8"
    - "10 x 2 = 20"
    - "14 ÷ 7 = 2"
    - "18 - 9 = 9"
    - "4 x 6 = 24"
    - "25 ÷ 5 = 5"
    - "11 + 4 = 15"
    - "13 - 6 = 7"
    - "3 x 8 = 24"
    - "9 x 2 = 18"
    - "20 ÷ 4 = 5"
    - "17 - 5 = 12"
    - "3 x 7 = 21"
    - "16 ÷ 2 = 8"
    - "19 - 8 = 11"
    - "12 x 2 = 24"
    - "30 ÷ 5 = 6"
    - "10 + 10 = 20"
    - "6 x 4 = 24"
    - "14 - 4 = 10"
    - "5 x 8 = 40"
    - "9 ÷ 3 = 3"
    - "18 + 7 = 25"
    - "13 + 2 = 15"
    - "7 x 3 = 21"
    - "11 ÷ 1 = 11"
    - "21 ÷ 7 = 3"
    - "20 + 4 = 24"
    - "8 x 4 = 32"
    - "15 ÷ 3 = 5"
    - "6 + 9 = 15"
    - "10 ÷ 2 = 5"
    - "13 x 2 = 26"
    - "17 + 3 = 20"
    - "8 ÷ 2 = 4"
    - "7 x 6 = 42"
    - "5 + 5 = 10"
    - "3 x 9 = 27"

who-am-i:
  time: 10
  words:
    - "Éjszaka jövök elő, és ha rám nézel, feldühítesz! = Enderman"
    - "Nappal égek, de éjszaka erősebb vagyok, ha megütnek! = Blaze"
    - "Hatalmas robbanást okozok, ha elég közel mész hozzám! = Creeper"
    - "Sötét helyeken bújkálok, és mérgezem a közelembe érkezőket! = Spider"
    - "Az esőben is szaporodok, és gyakran támadlak meg távolról! = Skeleton"
    - "Érintésem megölhet, ha nem vagy elég gyors! = Witch"
    - "Sosem vagyok egyedül, mindig hozok magammal egy kis sereget! = Zombified Piglin"
    - "Még a legnagyobb építkezők is tőlem rettegnek! = Silverfish"
    - "A víz alatt élek, és lassan megöllek, ha nem vigyázol! = Drowned"
    - "Sötét erdőkben rejtőzködöm, de ha meglátsz, támadni foglak! = Phantom"
    - "A föld alatti világomban élek, és lávát hozok magammal! = Magma Cube"
    - "Nagy és hatalmas vagyok, de nem támadok meg, ha nem provokálnak! = Iron Golem"
    - "Bárhova eljutok, és mindent elpusztítok, amit csak találok! = Ender Dragon"
    - "A jég világában élek, és gyorsan mozgok a hóban! = Stray"

word-stop:
  time: 15
  mobs:
    - "Z = Zombi"
    - "E = Enderman"
    - "S = Skeleton"
    - "C = Creeper"
    - "B = Blaze"
    - "D = Drowned"
    - "M = Magma Cube"
    - "V = Vindicator"
    - "W = Witch"
    - "P = Phantom"
    - "I = Iron Golem"
    - "F = Fox"
    - "L = Llama"
    - "G = Giant"
    - "S = Stray"
    - "A = Axolotl"
    - "T = Trader Llama"
    - "R = Ravager"
    - "W = Wolf"

word-guesser:
  time: 20
  words:
    - "Alma"
    - "Asztal"
    - "Számítógép"
    - "Tanul"
    - "Sziget"
    - "Irodalom"
    - "Elképesztő"
    - "Híd"
    - "Szerelem"
    - "Felhő"
    - "Képzelet"
    - "Nyugodt"
    - "Virág"
    - "Tudomány"
    - "Hosszú"
    - "Szórakozás"
    - "Megoldás"
    - "Erdő"
    - "Képesség"
    - "Elvárás"
    - "Megértés"
    - "Képzőművészet"
    - "Fantáziavilág"
    - "Szakértelem"
    - "Világítás"
    - "Tükröződés"
    - "Folyamatosság"
    - "Megszokás"
    - "Bonyolult"
    - "Összetett"
    - "Bölcsesség"
    - "Elvégzés"
    - "Összefonódás"
    - "Változékonyság"
    - "Türelmetlenség"
    - "Szemléletmód"
    - "Történelemkutatás"
    - "Felfedezés"
    - "Megvalósítás"
    - "Képességfejlesztés"
    - "Alkalmazkodóképesség"
    - "Szabadságvesztés"
    - "Előrelátó"
    - "Intellektuális"
    - "Kommunikációs"
    - "Elmélyedés"
    - "Légkörváltozás"
    - "Környezetvédelem"
    - "Skibidi"
    - "Goofy"
    - "Harcitandemelefánt"
    - "Eltöredezettségmentesítőtleníttethetetlenségtelenítőtlenkedhetnétek"
    - "Legeslegmegszentségteleníttethetetlenebbjeiteknek"
    - "Elkelkáposztástalaníthatatlanságoskodásaitokért"
    - "Megszentségteleníthetetlenségeskedéseitekért"
    - "KitPvP"
    - "FyreCoin"
    - "Lootbox"
    - "Gyémánt"
    - "BedWars"
    - "Kingdoms"
    - "SkyWars"
    - "Toplista"
    - "Szalonna"
    - "Fa"
    - "Szó"
    - "Toll"
    - "Áll"
    - "Mizu"
    - "Ok"
    - "Kő"
    - "Cölöp"
    - "Koma"
    - "Rolix"
    - "Répa"
    - "Sas"





