aliases:
  - "chatgame"
  - "mcchatgame"

rewards:
  - "[20] give {player} gold_ingot 1" # [chance] (command)
  - "[15] give {player} diamond 1"

time-between-games: 20
min-players: 2

random-characters:
  enabled: false
  time: 60
  length: 8

math:
  time: 60
  enabled: false
  problems:
    - "5 x 5 = 25"
    - "7 + 3 = 10"
    - "8 - 4 = 4"
    - "6 x 3 = 18"
    - "12 / 4 = 3"
    - "9 + 6 = 15"
    - "15 - 7 = 8"
    - "10 x 2 = 20"
    - "14 / 7 = 2"
    - "18 - 9 = 9"
    - "4 x 6 = 24"
    - "25 / 5 = 5"
    - "11 + 4 = 15"
    - "13 - 6 = 7"
    - "3 x 8 = 24"
    - "9 x 2 = 18"
    - "20 / 4 = 5"
    - "17 - 5 = 12"
    - "3 x 7 = 21"
    - "16 / 2 = 8"
    - "19 - 8 = 11"
    - "12 x 2 = 24"
    - "30 / 5 = 6"
    - "10 + 10 = 20"
    - "6 x 4 = 24"
    - "14 - 4 = 10"
    - "5 x 8 = 40"
    - "9 / 3 = 3"
    - "18 + 7 = 25"
    - "13 + 2 = 15"
    - "7 x 3 = 21"
    - "11 / 1 = 11"
    - "21 / 7 = 3"
    - "20 + 4 = 24"
    - "8 x 4 = 32"
    - "15 / 3 = 5"
    - "6 + 9 = 15"
    - "10 / 2 = 5"
    - "13 x 2 = 26"
    - "17 + 3 = 20"
    - "8 / 2 = 4"
    - "7 x 6 = 42"
    - "5 + 5 = 10"
    - "3 x 9 = 27"

who-am-i:
  time: 60
  enabled: false
  words:
    - "I sneak at night, my bones creak, and I shoot arrows at you! = Skeleton"
    - "I sneak up quietly, then explode loudly, leaving a giant hole! = Creeper"
    - "Sunlight is my enemy, but at night I’ll attack you! = Zombie"
    - "I strike in the darkness if you don’t sleep enough! = Phantom"
    - "I steal blocks, won’t attack unless you look into my eyes! = Enderman"
    - "I have three heads, I destroy hard, summon me and you better run! = Wither"
    - "I live in the forest, I watch you quietly, if you're kind to me, I’ll follow you! = Wolf"

word-stop:
  time: 60
  enabled: false
  mobs:
    - "Z = Zombie"
    - "E = Enderman"
    - "S = Skeleton"
    - "C = Creeper"
    - "W = Witch"
    - "P = Phantom"
    - "L = Llama"
    - "A = Axolotl"
    - "F = Fox"
    - "T = Turtle"
    - "S = Shulker"

word-guesser:
  time: 60
  enabled: false
  words:
    - "Apple"
    - "Desk"
    - "Computer"
    - "Studying"
    - "Island"
    - "Amazing"
    - "Bridge"
    - "Love"
    - "Cloud"

reverse:
  time: 60
  enabled: false
  words:
    - "Apple"
    - "Desk"
    - "Computer"
    - "Studying"
    - "Island"
    - "Amazing"
    - "Bridge"
    - "Love"
    - "Cloud"

fill-out:
  time: 60
  enabled: false
  words:
    - "Apple"
    - "Desk"
    - "Computer"
    - "Studying"
    - "Island"
    - "Amazing"
    - "Bridge"
    - "Love"
    - "Cloud"

crafting:
  time: 120
  enabled: true
  title: "&fCrafting &8» &#42f598&l{item}"
  crafts:
    "IRON_SHOVEL":
      items-to-place:
        - "STICK"
        - "STICK"
        - "IRON_INGOT"

streaks:
  enabled: true
  5:
    reach-message:
      enabled: true
      message:
        - ""
        - "&8&l&m--------------------------"
        - ""
        - " &8&l| &#42f598&l5 &a&lNEW STREAK"
        - ""
        - " &8&l| &f{player} reached streak 5!"
        - ""
        - "&8&l&m--------------------------"
        - ""
    lost-message:
      enabled: true
      message:
        - ""
        - "&8&l&m--------------------------"
        - ""
        - " &8&l| &#42f598&l5 &c&lSTREAK LOST"
        - ""
        - " &8&l| &f{player} reached streak 5!"
        - ""
        - "&8&l&m--------------------------"
        - ""
    commands:
      - "give {player} diamond 5"

database:
  type: "h2" # H2, MySQL

  mysql:
    host: "localhost"
    port: 3306
    database: "coma112"
    username: "root"
    password: ""

toast:
  enabled: true
  message: "&a&lSUCCESS GUESS!"
  material: "BOOK"

sounds:
  start:
    enabled: true
    sound: "minecraft:entity.zombie_villager.cure"
  win:
    enabled: true
    sound: "minecraft:entity.player.levelup"

placeholders:
  no-game: "&c&lNO GAME"
  fill-out: "&fFill out &8» &#42f598{word} &8(&#42f598{time}&8)"
  math: "&fMath &8» &#42f598{word} &8(&#42f598{time}&8)"
  random: "&fRandom Characters &8» &#42f598{word} &8(&#42f598{time}&8)"
  reverse: "&fReverse &8» &#42f598{word} &8(&#42f598{time}&8)"
  who-am-i: "&fWho am I &8» &#42f598{word} &8(&#42f598{time}&8)"
  word-guess: "&fWord Guess &8» &#42f598{word} &8(&#42f598{time}&8)"
  word-stop: "&fWord Guess &8» &#42f598{word} &8(&#42f598{time}&8)"
  crafting: "&fCrafting &8» &#42f598{word} &8(&#42f598{time}&8)"