aliases:
  - "chatgame"
  - "mcchatgame"

rewards:
  - "give {player} stick 1"

time-between-games: 20

random-characters:
  time: 60
  length: 8

math:
  time: 60
  problems:
    - "5 x 5 = 25"
    - "7 + 3 = 10"
    - "8 - 4 = 4"
    - "6 x 3 = 18"
    - "12 / 4 = 3"
    - "9 + 6 = 15"
    - "15 - 7 = 8"
    - "10 x 2 = 20"
    - "14 / 7 = 2"
    - "18 - 9 = 9"
    - "4 x 6 = 24"
    - "25 / 5 = 5"
    - "11 + 4 = 15"
    - "13 - 6 = 7"
    - "3 x 8 = 24"
    - "9 x 2 = 18"
    - "20 / 4 = 5"
    - "17 - 5 = 12"
    - "3 x 7 = 21"
    - "16 / 2 = 8"
    - "19 - 8 = 11"
    - "12 x 2 = 24"
    - "30 / 5 = 6"
    - "10 + 10 = 20"
    - "6 x 4 = 24"
    - "14 - 4 = 10"
    - "5 x 8 = 40"
    - "9 / 3 = 3"
    - "18 + 7 = 25"
    - "13 + 2 = 15"
    - "7 x 3 = 21"
    - "11 / 1 = 11"
    - "21 / 7 = 3"
    - "20 + 4 = 24"
    - "8 x 4 = 32"
    - "15 / 3 = 5"
    - "6 + 9 = 15"
    - "10 / 2 = 5"
    - "13 x 2 = 26"
    - "17 + 3 = 20"
    - "8 / 2 = 4"
    - "7 x 6 = 42"
    - "5 + 5 = 10"
    - "3 x 9 = 27"

who-am-i:
  time: 60
  words:
    - "Éjjel lopakodom, csontjaim recsegnek, és nyilakat lövök rád! = Csontváz"
    - "Halkan lopakodom, majd robbanok nagyot, óriás lyukat hagyok! = Creeper"
    - "A napfény az ellenségem, de éjszaka megtámadlak! = Zombi"
    - "A sötétségben lecsapok rád, ha nem alszol eleget! = Fantom"
    - "Blokkokat lopkodok, nem támadlak meg, amíg nem nézel a szemembe! = Enderman"
    - "Három fejem van, pusztítok erősen, ha megidézel, menekülj előlem! = Wither"
    - "Erdőben lakom, halkan lesek, ha kedves vagy hozzám, követlek! = Farkas"
    - "Nagy és erős, véd a bajban, de ne bánts mást, mert rád csap halkan! = Vasgólem"

word-stop:
  time: 60
  mobs:
    - "Z = Zombi"
    - "E = Enderman"
    - "Cs = Csontváz"
    - "C = Creeper"
    - "M = Magmakocka"
    - "B = Boszorkány"
    - "F = Fantom"
    - "V = Vasgólem"
    - "L = Láma"
    - "A = Axolotl"
    - "F = Farkas"
    - "R = Róka"
    - "T = Teknős"
    - "S = Shulker"
    - "W = Warden"

word-guesser:
  time: 60
  words:
    - "Alma"
    - "Asztal"
    - "Számítógép"
    - "Tanul"
    - "Sziget"
    - "Irodalom"
    - "Elképesztő"
    - "Híd"
    - "Szerelem"
    - "Felhő"
    - "Képzelet"
    - "Nyugodt"
    - "Virág"
    - "Tudomány"
    - "Hosszú"
    - "Szórakozás"
    - "Megoldás"
    - "Erdő"
    - "Képesség"
    - "Elvárás"
    - "Megértés"
    - "Képzőművészet"
    - "Fantáziavilág"
    - "Szakértelem"
    - "Világítás"
    - "Tükröződés"
    - "Folyamatosság"
    - "Megszokás"
    - "Bonyolult"
    - "Összetett"
    - "Bölcsesség"
    - "Elvégzés"
    - "Összefonódás"
    - "Változékonyság"
    - "Türelmetlenség"
    - "Szemléletmód"
    - "Történelemkutatás"
    - "Felfedezés"
    - "Megvalósítás"
    - "Képességfejlesztés"
    - "Alkalmazkodóképesség"
    - "Szabadságvesztés"
    - "Előrelátó"
    - "Intellektuális"
    - "Kommunikációs"
    - "Elmélyedés"
    - "Légkörváltozás"
    - "Környezetvédelem"
    - "Skibidi"
    - "Harcitandemelefánt"
    - "Megszentésgteleníthetetlenségeskedéseitekért"
    - "KitPvP"
    - "FyreCoin"
    - "Lootbox"
    - "Gyémánt"
    - "BedWars"
    - "Kingdoms"
    - "SkyWars"
    - "Toplista"
    - "Fa"
    - "Szó"
    - "Toll"
    - "Áll"
    - "Kő"
    - "Répa"
    - "Sas"
    - "Serpenyő"

reverse:
  time: 60
  words:
    - "Asztal"
    - "Számítógép"
    - "Tanul"
    - "Sziget"
    - "Irodalom"
    - "Elképesztő"
    - "Híd"
    - "Szerelem"
    - "Felhő"
    - "Képzelet"
    - "Nyugodt"
    - "Virág"
    - "Tudomány"
    - "Hosszú"
    - "Szórakozás"
    - "Megoldás"
    - "Erdő"
    - "Képesség"
    - "Elvárás"
    - "Megértés"
    - "Képzőművészet"
    - "Fantáziavilág"
    - "Szakértelem"
    - "Világítás"
    - "Tükröződés"
    - "Folyamatosság"
    - "Megszokás"
    - "Bonyolult"
    - "Összetett"
    - "Bölcsesség"
    - "Elvégzés"
    - "Összefonódás"
    - "Változékonyság"
    - "Türelmetlenség"
    - "Szemléletmód"
    - "Történelemkutatás"
    - "Felfedezés"
    - "Megvalósítás"
    - "Szabadságvesztés"
    - "Előrelátó"
    - "Intellektuális"
    - "Kommunikációs"
    - "Elmélyedés"
    - "Légkörváltozás"
    - "Környezetvédelem"
    - "KitPvP"
    - "FyreCoin"
    - "Lootbox"
    - "Gyémánt"
    - "BedWars"
    - "Kingdoms"
    - "SkyWars"
    - "Toplista"
    - "Fa"
    - "Szó"
    - "Toll"
    - "Áll"
    - "Kő"
    - "Répa"
    - "Sas"
    - "Serpenyő"

fill-out:
  time: 60
  words:
    - "Asztal"
    - "Számítógép"
    - "Tanul"
    - "Sziget"
    - "Irodalom"
    - "Elképesztő"
    - "Híd"
    - "Szerelem"
    - "Felhő"
    - "Képzelet"
    - "Nyugodt"
    - "Virág"
    - "Tudomány"
    - "Hosszú"
    - "Szórakozás"
    - "Megoldás"
    - "Erdő"
    - "Képesség"
    - "Elvárás"
    - "Megértés"
    - "Képzőművészet"
    - "Fantáziavilág"
    - "Szakértelem"
    - "Világítás"
    - "Tükröződés"
    - "Folyamatosság"
    - "Megszokás"
    - "Bonyolult"
    - "Összetett"
    - "Bölcsesség"
    - "Elvégzés"
    - "Összefonódás"
    - "Változékonyság"
    - "Türelmetlenség"
    - "Szemléletmód"
    - "Történelemkutatás"
    - "Felfedezés"
    - "Megvalósítás"
    - "Szabadságvesztés"
    - "Előrelátó"
    - "Intellektuális"
    - "Kommunikációs"
    - "Elmélyedés"
    - "Légkörváltozás"
    - "Környezetvédelem"
    - "KitPvP"
    - "FyreCoin"
    - "Lootbox"
    - "Gyémánt"
    - "BedWars"
    - "Kingdoms"
    - "SkyWars"
    - "Toplista"
    - "Répa"
    - "Serpenyő"

database:
  type: "h2" # H2, MySQL

  mysql:
    host: "localhost"
    port: 3306
    database: "coma112"
    username: "root"
    password: ""

toast:
  enabled: true
  message: "&a&lSUCCESS GUESS!"
  material: "BOOK"

sounds:
  start:
    enabled: true
    sound: "ENTITY_ZOMBIE_VILLAGER_CURE"
  win:
    enabled: true
    sound: "ENTITY_PLAYER_LEVELUP"

placeholders:
  no-game: "&c&lNO GAME"
  fill-out: "&fFill out &8» &#42f598{word} &8(&#42f598{time}&8)"
  math: "&fMath &8» &#42f598{word} &8(&#42f598{time}&8)"
  random: "&fRandom Characters &8» &#42f598{word} &8(&#42f598{time}&8)"
  reverse: "&fReverse &8» &#42f598{word} &8(&#42f598{time}&8)"
  who-am-i: "&fWho am I &8» &#42f598{word} &8(&#42f598{time}&8)"
  word-guess: "&fWord Guess &8» &#42f598{word} &8(&#42f598{time}&8)"
  word-stop: "&fWord Guess &8» &#42f598{word} &8(&#42f598{time}&8)"